name: CI
on:
- push
- pull_request
jobs:
  Python:
    strategy:
      matrix:
        include:
        - python: '3.3'
          os: ubuntu-18.04
        - python: '3.4'
          os: ubuntu-18.04
        - python: '3.5'
          os: ubuntu-18.04
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-20.04
        - python: '3.11-dev'
          os: ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: run tests
      run: |
        prove -v t/python*.t
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        pyflakes=pyflakes
        if [[ ${{matrix.python}} = 3.3 ]]; then pyflakes+='<2'; fi
        python3 -m pip install $pyflakes
        python3 -m pyflakes .
  HTML:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check HTML syntax
      run: |
        python3 -m pip install html5validator
        html5validator --also-check-css *.html
    - name: run tests
      run: |
        prove -v t/*js*.t
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
